### ISSUE TITLE
您好，请问您是如何定义节点样式的？

### ISSUE THREAD

**Issue by Sallyfafafa** [liangalien/kityminder-case-react#1]
这个位置的图标，是如何通过点击按钮，加到节点中进去的，我把你的代码翻了一遍也没有找到。

<img width="809" alt="image" src="https://user-images.githubusercontent.com/40735740/191682953-4e5a6313-b86a-4d59-80cc-87a744d01baf.png">

请求回复，谢谢🙏～

**Comment by liangalien** [comment]
需要修改kityminder-core的代码，我也传上来了，你可以参考一下
https://github.com/liangalien/kityminder-case-core/blob/2a027b29ea0479eb345dcaf9ee0562d8c91103aa/src/module/result.js
